### ISSUE TITLE
[Fix] 수정사항 및 구현 안된 부분 반영

### ISSUE THREAD

**Issue by suzinlim** [Youth-Fridge/youth-fridge-front#120]
## 어떤 기능인가요?
> 기획적인 수정사항과 구현이 미흡한 부분을 추가로 반영한다. 미반영된 부분은 새 이슈에서 다시 진행한다.

## 작업 상세 내용

- [x] 마이페이지 닉네임 반영
- [x] 초대장 생성할 때 닉네임 반영
- [ ] ~~마이페이지 문의 눌렀을 때 로직~~
- [ ] ~~홈에서 D-Day 상세한 반영~~
- [x] 신청한 소모임 확인 후 버튼 활성화/비활성화
- [ ] ~~전체적인 UI 비율 확인~~

**Comment by minsolkim** [comment]
마이페이지 닉네임 반영했습니당!!
